[package]
name = "assgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "1.0.0-alpha.18"
chrono = "0.4.0"
toml = "0.8.0"
serde = "*"
serde_derive = "*"
